import {
  tripGenerationRequestSchema,
  tripGenerationResponseSchema,
} from "./contracts";

export const mockJejuTripRequest = tripGenerationRequestSchema.parse({
  destination: "제주",
  duration: "1박2일",
  budgetPerPerson: 200000,
  groupSize: 4,
  styles: ["자연", "맛집", "힐링"],
  members: [
    { name: "멤버1", likes: ["카페", "사진"], dislikes: ["등산"] },
    { name: "멤버2", likes: ["맛집", "자연"], dislikes: [] },
  ],
});

export const mockJejuTripResponse = tripGenerationResponseSchema.parse({
  tripId: "trip_demo_jeju_001",
  summary: {
    totalEstimatedCost: 732000,
    estimatedCostPerPerson: 183000,
    budgetStatus: "within_budget",
  },
  route: [
    {
      day: 1,
      order: 1,
      time: "08:30",
      placeName: "김포공항 출발",
      category: "항공",
      estimatedCost: 35000,
      moveMinutesFromPrevious: 0,
      bookingUrl: "https://www.google.com/search?q=김포+제주+항공권",
      coordinates: { lat: 37.5583, lng: 126.7906 },
    },
    {
      day: 1,
      order: 2,
      time: "09:40",
      placeName: "제주공항 도착 및 렌터카 픽업",
      category: "교통",
      estimatedCost: 12000,
      moveMinutesFromPrevious: 70,
      bookingUrl: "https://www.google.com/maps/search/?api=1&query=제주국제공항",
      coordinates: { lat: 33.5071, lng: 126.4928 },
    },
    {
      day: 1,
      order: 3,
      time: "10:50",
      placeName: "성산일출봉",
      category: "자연",
      estimatedCost: 5000,
      moveMinutesFromPrevious: 55,
      bookingUrl: "https://www.google.com/maps/search/?api=1&query=성산일출봉",
      coordinates: { lat: 33.4581, lng: 126.9425 },
    },
    {
      day: 1,
      order: 4,
      time: "12:30",
      placeName: "성산 해녀의 집",
      category: "식사",
      estimatedCost: 20000,
      moveMinutesFromPrevious: 12,
      bookingUrl:
        "https://www.google.com/maps/search/?api=1&query=성산+해녀의+집",
      coordinates: { lat: 33.4712, lng: 126.931 },
    },
    {
      day: 1,
      order: 5,
      time: "15:00",
      placeName: "섭지코지",
      category: "자연",
      estimatedCost: 0,
      moveMinutesFromPrevious: 18,
      bookingUrl: "https://www.google.com/maps/search/?api=1&query=섭지코지",
      coordinates: { lat: 33.4239, lng: 126.9294 },
    },
    {
      day: 1,
      order: 6,
      time: "18:30",
      placeName: "동문시장 야시장",
      category: "식사",
      estimatedCost: 22000,
      moveMinutesFromPrevious: 45,
      bookingUrl: "https://www.google.com/maps/search/?api=1&query=제주+동문시장",
      coordinates: { lat: 33.5126, lng: 126.5289 },
    },
    {
      day: 2,
      order: 1,
      time: "09:30",
      placeName: "숙소 출발 및 서부권 이동",
      category: "교통",
      estimatedCost: 10000,
      moveMinutesFromPrevious: 0,
      bookingUrl: "https://www.google.com/maps/search/?api=1&query=제주+렌터카",
      coordinates: { lat: 33.4996, lng: 126.5312 },
    },
    {
      day: 2,
      order: 2,
      time: "10:30",
      placeName: "아르떼뮤지엄 제주",
      category: "사진",
      estimatedCost: 20000,
      moveMinutesFromPrevious: 35,
      bookingUrl:
        "https://www.google.com/maps/search/?api=1&query=아르떼뮤지엄+제주",
      coordinates: { lat: 33.3965, lng: 126.3448 },
    },
    {
      day: 2,
      order: 3,
      time: "13:00",
      placeName: "애월 고기국수",
      category: "식사",
      estimatedCost: 16000,
      moveMinutesFromPrevious: 20,
      bookingUrl:
        "https://www.google.com/maps/search/?api=1&query=애월+고기국수",
      coordinates: { lat: 33.4627, lng: 126.3092 },
    },
    {
      day: 2,
      order: 4,
      time: "15:00",
      placeName: "애월 카페거리",
      category: "카페",
      estimatedCost: 8000,
      moveMinutesFromPrevious: 35,
      bookingUrl:
        "https://www.google.com/maps/search/?api=1&query=애월+카페거리",
      coordinates: { lat: 33.5126, lng: 126.5289 },
    },
    {
      day: 2,
      order: 5,
      time: "18:00",
      placeName: "제주공항 복귀 및 항공권",
      category: "항공",
      estimatedCost: 35000,
      moveMinutesFromPrevious: 35,
      bookingUrl: "https://www.google.com/search?q=제주+김포+항공권",
      coordinates: { lat: 33.5071, lng: 126.4928 },
    },
  ],
});
